backstage:
  image:
    registry: ""
    repository: "${backstage_image}"
    tag: ""

  # Dedicated ServiceAccount created by Terraform (backstage.tf), not
  # chart-managed, so the RBAC in backstage-rbac.tf has a stable name
  # to bind to.
  serviceAccount:
    create: false
    name: "${service_account_name}"

  extraEnvVarsSecrets:
    - ${backend_secret_name}
%{ if enable_kubernetes_plugin }
    - ${k8s_token_secret_name}
%{ endif }

  appConfig:
    app:
      title: Platform Portal
      baseUrl: "${backstage_base_url}"

    backend:
      baseUrl: "${backstage_base_url}"
      listen:
        port: 7007
      cors:
        origin: "${backstage_base_url}"
      # Recent Backstage backends require a signing key for
      # service-to-service auth or the backend will refuse to start.
      # BACKEND_SECRET is injected from a generated Kubernetes Secret
      # (see terraform/backstage.tf) via extraEnvVarsSecrets.
      #
      # NOTE: no dangerouslyDisableDefaultAuthPolicy here on purpose.
      # Configure a real sign-in provider (GitHub/Google/OIDC, or at
      # minimum the guest provider for a controlled internal rollout)
      # in your Backstage app's backend index.ts before deploying this.
      # Every catalog/API request will 401 until a real identity flow
      # is wired up.
      auth:
        keys:
          - secret: $${BACKEND_SECRET}
      reading:
        allow:
          - host: "*.vela-system.svc.cluster.local:8080"

%{ if enable_kubernetes_plugin }
    # Live pod/deployment status on entity pages. Requires the
    # @backstage/plugin-kubernetes frontend package to be installed and
    # added to your app's features (or EntityPage, on the old frontend
    # system). K8S_SA_TOKEN comes from the Secret backstage.tf creates
    # for the dedicated ServiceAccount, see backstage-rbac.tf for what
    # it can read.
    kubernetes:
      serviceLocatorMethod:
        type: multiTenant
      clusterLocatorMethods:
        - type: config
          clusters:
            - url: https://kubernetes.default.svc
              name: local
              authProvider: serviceAccount
              serviceAccountToken: $${K8S_SA_TOKEN}
              skipTLSVerify: true
              skipMetricsLookup: true
%{ endif }

    # This is what actually bridges the two tools: KubeVela Applications
    # get polled and mirrored into the Backstage catalog as entities.
    #
    # IMPORTANT: this config shape matches the NEW backend system
    # (backend.add(...) in packages/backend/src/index.ts), see
    # backstage/catalog-plugin-wiring.ts for the corresponding backend
    # module code. Config is still a flat `vela:` block at the root of
    # app-config, not nested under catalog.providers.vela.<id>, because
    # @oamdev/plugin-kubevela-backend's VelaProvider class reads it that
    # way regardless of which backend system wires it in.
    vela:
      host: "${kubevela_plugin_host}"
      frequency: 30
      timeout: 60

    catalog:
      locations:
        # Working reference entity, see examples/sample-app/. Your
        # Backstage app image needs this file copied into its own
        # examples/ (or wherever its Dockerfile expects static catalog
        # locations to live) -- this repo doesn't control your app's
        # Docker build, only the cluster-side config that points at it.
        - type: file
          target: /app/examples/sample-app/catalog-info.yaml

postgresql:
  enabled: true
  auth:
    database: backstage
    username: backstage
    # Generated by Terraform (backstage.tf), never hardcoded here.
    # Bitnami's postgresql subchart expects these two key names by
    # default when existingSecret is used.
    existingSecret: "${postgres_secret_name}"

ingress:
  enabled: false
  # Set to true and configure a host/className/tls block once you have
  # a real Ingress controller and DNS record pointed at this cluster.
  # backstage_base_url (above) must match whatever host you set here.
